"""
Day 1 - Part 2 补充: 字符串加强训练
场景：更贴近 CAD 工程师实际工作中遇到的字符串处理
"""

# ============================================================
# 练习 4: 解析 Spectre 模型参数行
# ============================================================
# 给定一行 Spectre 参数定义，提取所有参数名和值存到字典中
# 注意: 有些参数值带单位，有些不带

param_line = "parameters vth0=0.45 toxe=1.85e-9 u0=320 vsat=1.2e5 rdsw=150"

# 期望输出（字典）:
# {"vth0": 0.45, "toxe": 1.85e-09, "u0": 320.0, "vsat": 120000.0, "rdsw": 150.0}
# 提示: 第一个 token "parameters" 是关键字，要跳过

# >>> 在这里写代码 <<<
expected_dict = {}
param_list = param_line.split()[1:]
for param in param_list:
    key, value = param.split("=") # 将 "vth0=0.45" 分成 ["vth0", "0.45"]
    expected_dict[key] = float(value) #所以value是字符串，需要转换成数字
print(expected_dict)

# ============================================================
# 练习 5: 批量生成 corner 名称
# ============================================================
# 根据 process/voltage/temperature 组合，生成 corner 名
# 格式: {process}_{voltage}V_{temp}C
# 例如: "tt_1.8V_25C"

processes = ["ss", "tt", "ff"]
voltages = [1.62, 1.8, 1.98]
temps = [-40, 25, 125]

# 用嵌套循环 + f-string 生成所有 corner 名称，存到列表里
# 最后打印总数和前 5 个 corner 名

# >>> 在这里写代码 <<<
corner_names = []
for p in processes:
    for v in voltages:
        for t in temps:
            corner_names.append(f'{p}_{v}V_{t}C')
print(f"Total corners: {len(corner_names)}")
print("First 5 corners:", corner_names[:5])


# ============================================================
# 练习 6: 从文件路径中提取信息
# ============================================================
# 从仿真结果路径中解析出各个字段

sim_paths = [
    "/proj/ldo_2024/user/josn/sim/LDO_TOP/tt_25c/run_003/spectre.log",
    "/proj/ldo_2024/user/mike/sim/BANDGAP/ff_m40c/run_012/spectre.log",
    "/proj/pll_2025/user/josn/sim/VCO_CORE/ss_125c/run_001/spectre.log",
]

# 对每条路径，提取并打印: project, user, cell, corner, run_id
# 期望输出格式:
#   Project: ldo_2024 | User: josn | Cell: LDO_TOP | Corner: tt_25c | Run: 3

# >>> 在这里写代码 <<<
path_info_list = []
for path in sim_paths:
    path_info_list = path.split("/") #split()分离的第0个元素是空字符串，因为路径以/开头，所以第一个元素是空的，所以索引时从2开始
    print(f"Project: {path_info_list[2]} | User: {path_info_list[4]} | Cell: {path_info_list[6]} | Corner: {path_info_list[7]} | Run: {int(path_info_list[8].split('_')[1])}") #run期望的是拿的数字


# ============================================================
# 练习 7: Netlist 注释清理
# ============================================================
# 清理 netlist 内容：去掉注释行（以 * 或 // 开头）和行内注释（// 后面的部分）
# 去掉空行，返回干净的 netlist

raw_netlist = """
* HSPICE netlist for LDO_TOP
// Generated by Calibre xRC

.subckt LDO_TOP VIN VOUT VSS
R0 VIN net1 10k   // feedback resistor
R1 net1 VSS 20k
C0 VOUT VSS 1p    // load cap
* M0 net1 net2 VDD VSS nmos w=2u l=180n
.ends LDO_TOP

"""

# 期望输出（每行一个元素的列表）:
# [".subckt LDO_TOP VIN VOUT VSS",
#  "R0 VIN net1 10k",
#  "R1 net1 VSS 20k",
#  "C0 VOUT VSS 1p",
#  ".ends LDO_TOP"]

# >>> 在这里写代码 <<<
netlist_pure = []
netlist_split = raw_netlist.split('\n')
for line in netlist_split:
    if line.startswith("//") or line.startswith("*") or line.strip() == "":
        continue  # 跳过注释行和空行
    #else:   #else → 把整行（带 // feedback resistor）加进去了
    #    netlist_pure.append(line.strip()) #加入需要的正常行，并去掉行首尾的空白 
    if "//" in line:
        netlist_pure.append(line.split("//")[0].strip()) # 如果行内有注释，保留注释前的部分，并去掉多余空白
    else:
        netlist_pure.append(line.strip()) # 没有行内注释的正常行，直接去掉首尾空白加入结果列表
print(netlist_pure)        

# ============================================================
# 练习 8: 版本号比较
# ============================================================
# 比较两个 cell 的版本号，判断哪个更新
# 版本格式: "v{major}.{minor}.{patch}" 例如 "v2.1.3"
# 比较规则: 先比 major，再比 minor，最后比 patch

version_pairs = [
    ("v1.2.3", "v1.2.4"),
    ("v2.0.0", "v1.9.9"),
    ("v1.3.0", "v1.3.0"),
    ("v0.10.1", "v0.9.12"),
]

# 对每一对打印: "v1.2.3 < v1.2.4" 或 "v2.0.0 > v1.9.9" 或 "v1.3.0 == v1.3.0"

# >>> 在这里写代码 <<<
for v1,v2 in version_pairs:
    v1_split = list(map(int,v1[1:].split('.'))) # v1[1:]去掉开头的"v"，得到"1.2.3"，再用split('.')分成["1","2","3"]，最后用map(int,...)把每个字符串转换成整数，得到[1,2,3]
    v2_split = list(map(int,v2[1:].split('.')))
    if v1_split < v2_split:   #列表的比较是逐元素比较的，先比较第一个元素，如果相等再比较第二个，以此类推
        print(f"{v1} < {v2}")
    elif v1_split > v2_split:
        print(f"{v1} > {v2}")
    else:
        print(f"{v1} == {v2}")


# ============================================================
# 练习 9: 对齐打印仿真结果表格
# ============================================================
# 把仿真结果格式化成对齐的表格输出

sim_results = [
    ("tt_25c",  45.67, 62.3, 125.8),
    ("ss_125c", 38.21, 55.1, 89.3),
    ("ff_m40c", 52.04, 70.8, 198.2),
    ("ss_m40c", 36.88, 51.2, 75.6),
]

# 期望输出（列对齐）:
# Corner     | Gain(dB) | PM(deg) | GBW(MHz)
# -----------+-----------+---------+---------
# tt_25c     |     45.67 |    62.3 |   125.8
# ss_125c    |     38.21 |    55.1 |    89.3
# ff_m40c    |     52.04 |    70.8 |   198.2
# ss_m40c    |     36.88 |    51.2 |    75.6
# 提示: f-string 对齐语法 {value:>10.2f} 右对齐宽度10保留2位小数

# >>> 在这里写代码 <<<
print(f"{'Corner':15} | {'Gain(dB)':15} | {'PM(deg)':15} | {'GBW(MHz)':15}") #每列宽度15，左对齐，列名分别是Corner、Gain(dB)、PM(deg)、GBW(MHz)
print("-" * 15 + "+" + "-" * 15 + "+" + "-" * 15 + "+" + "-" * 15) # 打印分隔线，每列15个"-"，列之间用"+"分隔
for corner, gain, pm, gbw in sim_results:
    print(f"{corner:15} | {gain:15.2f} | {pm:15.1f} | {gbw:15.1f}") #每列宽度15，corner左对齐，gain、pm、gbw右对齐，gain保留2位小数，pm和gbw保留1位小数
